// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'BaseType' in declaration 'DerivedClass' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'MemberType, NullableType' in declaration 'DerivedClass._field1' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'TypeOf' in declaration 'DerivedClass._field2' (SyntaxKind=IdentifierName).`
// Warning MY001 on `VirtualMethod`: `Reference constraint of type 'OverrideMember' in declaration 'DerivedClass.VirtualMethod()' (SyntaxKind=MethodDeclaration).`
// Warning MY001 on `base.VirtualMethod`: `Reference constraint of type 'Invocation' in declaration 'DerivedClass.VirtualMethod()' (SyntaxKind=SimpleMemberAccessExpression).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'ReturnType, NullableType' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'ParameterType, ArrayType' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)/param1' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'TypeArgument, ParameterType' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)/param2' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'LocalVariableType' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `new()`: `Reference constraint of type 'ObjectCreation' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=ImplicitObjectCreationExpression).`
// Warning MY001 on `var`: `Reference constraint of type 'LocalVariableType' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `new ValidatedClass()`: `Reference constraint of type 'ObjectCreation' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=ObjectCreationExpression).`
// Warning MY001 on `InstanceField`: `Reference constraint of type 'Default' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `x.InstanceField`: `Reference constraint of type 'Assignment' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=SimpleMemberAccessExpression).`
// Warning MY001 on `x.InstanceField`: `Reference constraint of type 'Assignment' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=SimpleMemberAccessExpression).`
// Warning MY001 on `StaticField`: `Reference constraint of type 'Assignment' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `Method`: `Reference constraint of type 'Invocation' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'TypeOf' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'NameOf' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `InstanceField`: `Reference constraint of type 'NameOf' in declaration 'DerivedClass.Method(ValidatedClass[], List<ValidatedClass>)' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'MemberType, NullableType' in declaration 'DerivedClass.Property' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedDelegate`: `Reference constraint of type 'MemberType, NullableType' in declaration 'DerivedClass.FieldLikeEvent' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedDelegate`: `Reference constraint of type 'MemberType' in declaration 'DerivedClass.ExplicitEvent' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'LocalVariableType' in declaration 'ReferencingClass.ReferencingMethod()' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass.Method`: `Reference constraint of type 'Invocation' in declaration 'ReferencingClass.ReferencingMethod()' (SyntaxKind=SimpleMemberAccessExpression).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'TypeOf' in declaration 'ReferencingClass.ReferencingMethod()' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'TypeArgument, LocalVariableType' in declaration 'ReferencingClass.ReferencingMethod()' (SyntaxKind=IdentifierName).`
// Warning MY001 on `ValidatedClass`: `Reference constraint of type 'TypeArgument' in declaration 'ReferencingClass.ReferencingMethod()' (SyntaxKind=IdentifierName).`