// CompileTimeAspectPipeline.ExecuteAsync failed.
// Error LAMA0037 on `ImplicitlyInstanceExplicitlyVirtualIntroduction`: `The aspect 'ImplicitlyInstanceExplicitlyVirtualIntroduction' cannot be applied to the type 'TargetStruct' because the aspect contains an virtual declarative introduction and therefore cannot be applied to sealed types, static types and structs.`
// Error LAMA0037 on `ImplicitlyInstanceImplicitlyVirtualIntroduction`: `The aspect 'ImplicitlyInstanceImplicitlyVirtualIntroduction' cannot be applied to the type 'TargetStruct' because the aspect contains an virtual declarative introduction and therefore cannot be applied to sealed types, static types and structs.`
// Error LAMA0037 on `ExplicitlyInstanceExplicitlyVirtualIntroduction`: `The aspect 'ExplicitlyInstanceExplicitlyVirtualIntroduction' cannot be applied to the type 'TargetStruct' because the aspect contains an virtual declarative introduction and therefore cannot be applied to sealed types, static types and structs.`
// Error LAMA0037 on `ImplicitlyInstanceExplicitlyVirtualIntroduction`: `The aspect 'ImplicitlyInstanceExplicitlyVirtualIntroduction' cannot be applied to the type 'SealedTargetClass' because the aspect contains an virtual declarative introduction and therefore cannot be applied to sealed types, static types and structs.`
// Error LAMA0037 on `ImplicitlyInstanceImplicitlyVirtualIntroduction`: `The aspect 'ImplicitlyInstanceImplicitlyVirtualIntroduction' cannot be applied to the type 'SealedTargetClass' because the aspect contains an virtual declarative introduction and therefore cannot be applied to sealed types, static types and structs.`
// Error LAMA0037 on `ExplicitlyInstanceExplicitlyVirtualIntroduction`: `The aspect 'ExplicitlyInstanceExplicitlyVirtualIntroduction' cannot be applied to the type 'SealedTargetClass' because the aspect contains an virtual declarative introduction and therefore cannot be applied to sealed types, static types and structs.`
// Error LAMA0037 on `ImplicitlyInstanceExplicitlyVirtualIntroduction`: `The aspect 'ImplicitlyInstanceExplicitlyVirtualIntroduction' cannot be applied to the type 'StaticTargetClass' because the aspect contains an instance declarative introduction and therefore cannot be applied to static types.`
// Error LAMA0037 on `ImplicitlyInstanceImplicitlyVirtualIntroduction`: `The aspect 'ImplicitlyInstanceImplicitlyVirtualIntroduction' cannot be applied to the type 'StaticTargetClass' because the aspect contains an instance declarative introduction and therefore cannot be applied to static types.`
// Error LAMA0037 on `ExplicitlyInstanceExplicitlyVirtualIntroduction`: `The aspect 'ExplicitlyInstanceExplicitlyVirtualIntroduction' cannot be applied to the type 'StaticTargetClass' because the aspect contains an instance declarative introduction and therefore cannot be applied to static types.`