// CompileTimeAspectPipeline.ExecuteAsync failed.
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.Deconstruct(out string)': Cannot add an OverrideMethod advice to 'Person.Deconstruct(out string)' because 'Person.Deconstruct(out string)' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.Equals(Person?)': Cannot add an OverrideMethod advice to 'Person.Equals(Person?)' because 'Person.Equals(Person?)' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.Equals(object?)': Cannot add an OverrideMethod advice to 'Person.Equals(object?)' because 'Person.Equals(object?)' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.GetHashCode()': Cannot add an OverrideMethod advice to 'Person.GetHashCode()' because 'Person.GetHashCode()' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.PrintMembers(StringBuilder)': Cannot add an OverrideMethod advice to 'Person.PrintMembers(StringBuilder)' because 'Person.PrintMembers(StringBuilder)' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.ToString()': Cannot add an OverrideMethod advice to 'Person.ToString()' because 'Person.ToString()' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.operator !=(Person?, Person?)': Cannot add an OverrideMethod advice to 'Person.operator !=(Person?, Person?)' because 'Person.operator !=(Person?, Person?)' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Person`: `'OverrideMethodAspect.BuildAspect' threw 'InvalidOperationException' when applied to 'Person.operator ==(Person?, Person?)': Cannot add an OverrideMethod advice to 'Person.operator ==(Person?, Person?)' because 'Person.operator ==(Person?, Person?)' must be explicitly declared. Check the IsAdviceEligible(AdviceKind.OverrideMethod) method. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
