// CompileTimeAspectPipeline.ExecuteAsync failed.
// Error LAMA0041 on `SyncVoid`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskAttribute] applied to 'TargetClass.SyncVoid()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.SyncVoid()': the template return type 'Task' is not compatible with the type of the target method 'void'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncVoid`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskDynamicAttribute] applied to 'TargetClass.SyncVoid()': Cannot use the template 'TaskDynamicAttribute.Template()' to override the method 'TargetClass.SyncVoid()': the template return type 'Task<dynamic?>' is not compatible with the type of the target method 'void'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Int`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskAttribute] applied to 'TargetClass.Int()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.Int()': the template return type 'Task' is not compatible with the type of the target method 'int'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Int`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskDynamicAttribute] applied to 'TargetClass.Int()': Cannot use the template 'TaskDynamicAttribute.Template()' to override the method 'TargetClass.Int()': the template return type 'Task<dynamic?>' is not compatible with the type of the target method 'int'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncTaskInt`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskAttribute] applied to 'TargetClass.SyncTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.SyncTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'Task<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncTaskInt`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskAttribute] applied to 'TargetClass.AsyncTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.AsyncTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'Task<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncValueTaskInt`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskAttribute] applied to 'TargetClass.SyncValueTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.SyncValueTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'ValueTask<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncValueTaskInt`: `'Exception of type 'Metalama.Framework.Aspects.InvalidTemplateSignatureException' thrown while executing BuildAspect for aspect [TaskAttribute] applied to 'TargetClass.AsyncValueTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.AsyncValueTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'ValueTask<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
