// CompileTimeAspectPipeline.ExecuteAsync failed.
// Error LAMA0041 on `SyncVoid`: `'TaskAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncVoid()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.SyncVoid()': the template return type 'Task' is not compatible with the type of the target method 'void'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncVoid`: `'TaskDynamicAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncVoid()': Cannot use the template 'TaskDynamicAttribute.Template()' to override the method 'TargetClass.SyncVoid()': the template return type 'Task<dynamic?>' is not compatible with the type of the target method 'void'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Int`: `'TaskAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.Int()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.Int()': the template return type 'Task' is not compatible with the type of the target method 'int'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Int`: `'TaskDynamicAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.Int()': Cannot use the template 'TaskDynamicAttribute.Template()' to override the method 'TargetClass.Int()': the template return type 'Task<dynamic?>' is not compatible with the type of the target method 'int'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `Int`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.Int()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.Int()': the template return type 'void' is not compatible with the type of the target method 'int'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncTask`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncTask()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.SyncTask()': the template return type 'void' is not compatible with the type of the target method 'Task'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncTask`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.AsyncTask()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.AsyncTask()': the template return type 'void' is not compatible with the type of the target method 'Task'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncTaskInt`: `'TaskAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.SyncTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'Task<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncTaskInt`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncTaskInt()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.SyncTaskInt()': the template return type 'void' is not compatible with the type of the target method 'Task<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncTaskInt`: `'TaskAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.AsyncTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.AsyncTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'Task<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncTaskInt`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.AsyncTaskInt()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.AsyncTaskInt()': the template return type 'void' is not compatible with the type of the target method 'Task<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncValueTask`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncValueTask()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.SyncValueTask()': the template return type 'void' is not compatible with the type of the target method 'ValueTask'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncValueTask`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.AsyncValueTask()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.AsyncValueTask()': the template return type 'void' is not compatible with the type of the target method 'ValueTask'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncValueTaskInt`: `'TaskAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncValueTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.SyncValueTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'ValueTask<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `SyncValueTaskInt`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.SyncValueTaskInt()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.SyncValueTaskInt()': the template return type 'void' is not compatible with the type of the target method 'ValueTask<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncValueTaskInt`: `'TaskAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.AsyncValueTaskInt()': Cannot use the template 'TaskAttribute.Template()' to override the method 'TargetClass.AsyncValueTaskInt()': the template return type 'Task' is not compatible with the type of the target method 'ValueTask<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
// Error LAMA0041 on `AsyncValueTaskInt`: `'VoidAttribute.BuildAspect' threw 'InvalidTemplateSignatureException' when applied to 'TargetClass.AsyncValueTaskInt()': Cannot use the template 'VoidAttribute.Template()' to override the method 'TargetClass.AsyncValueTaskInt()': the template return type 'void' is not compatible with the type of the target method 'ValueTask<int>'. Exception details are in '(none)'. To attach a debugger to the compiler, use the  '-p:MetalamaDebugCompiler=True' command-line option.`
