// Copyright (c) SharpCrafters s.r.o. All rights reserved.
// This project is not open source. Please see the LICENSE.md file in the repository root for details.

namespace Metalama.Framework.Tests.UnitTests.Licensing
{
    internal static class TestLicenseKeys
    {
        public const string MetalamaStarterBusiness
            = "3-ZUQQQQQQZUAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7EAED3WYKF9V8KYEUMGXKBYPRQNNUVQDV3BHMGEHNJHLBKGSD57EEJQRD4F3SWWEA42CUZQQDEZJGP4Q8USJG4X6P2";

        public const string MetalamaProfessionalBusiness
            = "4-ZQAQQQQQZTAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7EAEGGU48KSPSAKJRSXFLZAF72CTB3QUMT9RR6WTPVYSNJT46PKU645EAPBXKGNFCJPVKZQQDEZJGP4Q8USJG4X6P2";

        public const string MetalamaUltimateBusiness
            = "1-ZEQQQQQQZEAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7EAEASD8CXFHZY99JSJCPGSS6F3Q258BHCEBQCCLP85GRPFUZWBPAKLCV8CDZQ3JUUZFPZQQDEZJGP4Q8USJG4X6P2";

        public const string MetalamaUltimateEssentials
            = "2-ZTQQQQQQAEAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7EAEJNYQZ645W4ZPHXRWCAW2WVVGKMS4FAAFH6W6FCBMXTNX5PHLC9X5HT92MNBVUKMQUZQQDEZJGP4Q8USJG4X6P2";

        public const string MetalamaUltimateOpenSourceRedistribution
            = "5-ZEAQQQQQXEAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7EAEAPQPUW2VKAJDJ45JUQENSNR7N3L5PGFRUVNNYP3CTNN4DE2U6PTPXWC9UA2GDLGPMZQQDEZJGP4Q8USJG4X6P2";

        public const string NamespaceLimitedMetalamaUltimateBusinessNamespace = "NonRedistributionTests.TargetNamespace";

        public const string NamespaceLimitedMetalamaUltimateBusiness
            = "6-ZTAQQQQQZEAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7YQXG6LX7DCS2JBNJGVB4MWNMGVD88KXCHR629X37TCA6KVNBGVVCUMNBFVT4UXNBDAEJVU2BU4NZCND5MQR3M9ZHSUEXFPJG72M4AZQUHMXKBYDQW8HW82EWDWJARNVBKDXUZQQDEZJGP4Q8USJG4X6P2";

        public const string NamespaceLimitedMetalamaUltimateEssentialsNamespace = "NonRedistributionTests.TargetNamespace";

        public const string NamespaceLimitedMetalamaUltimateEssentials
            = "7-ZUAQQQQQAEAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7YQXG6LX7DCS2JBNJGVB4MWNMGVD88KXCHR629X37TCA6KVNBGVVCUMNBFVT4UXNBDAEGJWZ6TP8JERU7V5K73HB6R4EMBRKNPKAY7ZQX64DMXYEL267CDWQKPSPS76VZYHS8ZQQDEZJGP4Q8USJG4X6P2";

        public const string NamespaceLimitedMetalamaUltimateOpenSourceRedistributionNamespace = "RedistributionTests.TargetNamespace";

        public const string NamespaceLimitedMetalamaUltimateOpenSourceRedistribution
            = "8-ZQZQQQQQXEAEQCRCE4UW3UFEB4URXMHRB8KQBJJSB64LX7YQ2GYCXBSF629W7YDRH29BN7JFYCJX3MFVVAHZXJ9RS29KYTHFS8KQ7TFRS6ZTBVWZLKJVF3HZZHWA4ZKSX3DXZYBKR4MWCZF4AW43L2DLEPB5T8HFVMFKBYLUG2X78SQQBTWB2P7QNG4B27RXP3";
    }
}