// CompileTimeAspectPipeline.ExecuteAsync failed.
// Error LAMA0115 on `meta.Target.Field.Name`: `The advice 'AspectBase.Template()' cannot use 'meta.Field' in an advice applied to method 'TargetCode.field.get' because there is no 'IField'. Consider using meta.FieldOrProperty instead.`
// Error LAMA0115 on `meta.Target.Indexer.Name`: `The advice 'AspectBase.Template()' cannot use 'meta.Indexer' in an advice applied to method 'TargetCode.field.get' because there is no 'IIndexer'.`
// Error LAMA0115 on `field`: `The advice 'AspectBase.Template()' cannot use 'meta.Property' in an advice applied to method 'TargetCode.get_field' because there is no 'IProperty'. Consider using meta.FieldOrProperty instead.`
// Error LAMA0115 on `get`: `The advice 'AspectBase.Template()' cannot use 'meta.Field' in an advice applied to method 'TargetCode.property.get' because there is no 'IField'. Consider using meta.FieldOrProperty instead.`
// Error LAMA0115 on `get`: `The advice 'AspectBase.Template()' cannot use 'meta.Indexer' in an advice applied to method 'TargetCode.property.get' because there is no 'IIndexer'.`
// Error LAMA0115 on `=> 42`: `The advice 'AspectBase.Template()' cannot use 'meta.Field' in an advice applied to method 'TargetCode.this[int].get' because there is no 'IField'. Consider using meta.FieldOrPropertyOrIndexer instead.`
// Error LAMA0115 on `=> 42`: `The advice 'AspectBase.Template()' cannot use 'meta.FieldOrProperty' in an advice applied to method 'TargetCode.this[int].get' because there is no 'IFieldOrProperty'. Consider using meta.FieldOrPropertyOrIndexer instead.`
// Error LAMA0115 on `=> 42`: `The advice 'AspectBase.Template()' cannot use 'meta.Property' in an advice applied to method 'TargetCode.this[int].get' because there is no 'IProperty'. Consider using meta.FieldOrPropertyOrIndexer instead.`
