// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using JetBrains.Annotations;
using Metalama.Framework.Aspects;

namespace Metalama.Framework.Introspection;

[PublicAPI]
public interface IIntrospectionAspectLayer
{
    /// <summary>
    /// Gets the aspect layer identifier.
    /// </summary>
    string Id { get; }

    /// <summary>
    /// Gets the aspect class.
    /// </summary>
    IIntrospectionAspectClass AspectClass { get; }

    /// <summary>
    /// Gets the name of the layer, or <c>null</c> for the default layer.
    /// </summary>
    string? LayerName { get; }

    /// <summary>
    /// Gets the actual order in which the layer is executed against the code model, which typically the
    /// inverse order in which the code generated by the layer is executed. This order is determined by
    /// evaluating the set of <see cref="AspectOrderAttribute"/> attributes, and applying alphabetical sort
    /// to resolve ambiguities. To get the order that relies only on <see cref="AspectOrderAttribute"/> attributes, without
    /// alphabetical ordering, see <see cref="ExplicitOrder"/>. 
    /// </summary>
    int? Order { get; }

    /// <summary>
    /// Gets the aspect layer execution order given by the <see cref="AspectOrderAttribute"/> attributes.
    /// Several layers can have the same value for the <see cref="ExplicitOrder"/> property if ordering is incomplete.
    /// For the actual execution order without ambiguities, see the <see cref="Order"/> property. 
    /// </summary>
    int? ExplicitOrder { get; }

    /// <summary>
    /// Gets a value indicating whether the layer is the default layer of the <see cref="AspectClass"/>.
    /// </summary>
    bool IsDefaultLayer { get; }
}