
// --- NamespaceLimitedRedistributionDisallowed.cs ---

// CompileTimeAspectPipeline.ExecuteAsync failed. 
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect1' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect1' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect4' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect4' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect1' aspect.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect2' aspect.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect3' aspect.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect4' aspect.`
// Error LAMA0800 on ``: `You have 4 aspect classes used in the project but only 3 are allowed by your license. The aspect classes are: 'RedistributionAspect1', 'RedistributionAspect2', 'RedistributionAspect3', 'RedistributionAspect4'.`


// --- _Redistribution.cs ---

// CompileTimeAspectPipeline.ExecuteAsync failed. 
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect1' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect1' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect2' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect4' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0035 on ``: `The aspect layers 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect3' and 'Metalama.Framework.Tests.Integration.Tests.Licensing.Redistribution.Dependency.RedistributionAspect4' are not strongly ordered. Add an [assembly: AspectOrderAttribute(...)] attribute to specify the order relationship between these two layers, otherwise the compilation will be non-deterministic.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect1' aspect.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect2' aspect.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect3' aspect.`
// Warning LAMA0803 on ``: `The redistribution license of 'dependency_XXXXXXXXXXXXXXXX' assembly is invalid for 'RedistributionAspect4' aspect.`
// Error LAMA0800 on ``: `You have 4 aspect classes used in the project but only 3 are allowed by your license. The aspect classes are: 'RedistributionAspect1', 'RedistributionAspect2', 'RedistributionAspect3', 'RedistributionAspect4'.`

