#pragma warning disable CS8669 // Nullability
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Metalama.Framework.Engine.CompileTime;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Metalama.Framework.Engine.Utilities.Roslyn;

public static class SyntaxNodePartialUpdateExtensions
{
	public readonly struct Option<T>( T value )
	{
		public T? GetValueOrDefault() => value;
		public bool HasValue { get; } = true;
		public static implicit operator Option<T>( T value ) => new( value );
	}
	public static IdentifierNameSyntax PartialUpdate(
		this IdentifierNameSyntax node,
		Option<SyntaxToken> identifier = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static QualifiedNameSyntax PartialUpdate(
		this QualifiedNameSyntax node,
		Option<NameSyntax> left = default,
		Option<SyntaxToken> dotToken = default,
		Option<SimpleNameSyntax> right = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static GenericNameSyntax PartialUpdate(
		this GenericNameSyntax node,
		Option<SyntaxToken> identifier = default,
		Option<TypeArgumentListSyntax> typeArgumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeArgumentListSyntax PartialUpdate(
		this TypeArgumentListSyntax node,
		Option<SyntaxToken> lessThanToken = default,
		Option<SeparatedSyntaxList<TypeSyntax>> arguments = default,
		Option<SyntaxToken> greaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AliasQualifiedNameSyntax PartialUpdate(
		this AliasQualifiedNameSyntax node,
		Option<IdentifierNameSyntax> alias = default,
		Option<SyntaxToken> colonColonToken = default,
		Option<SimpleNameSyntax> name = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PredefinedTypeSyntax PartialUpdate(
		this PredefinedTypeSyntax node,
		Option<SyntaxToken> keyword = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ArrayTypeSyntax PartialUpdate(
		this ArrayTypeSyntax node,
		Option<TypeSyntax> elementType = default,
		Option<SyntaxList<ArrayRankSpecifierSyntax>> rankSpecifiers = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ArrayRankSpecifierSyntax PartialUpdate(
		this ArrayRankSpecifierSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<ExpressionSyntax>> sizes = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PointerTypeSyntax PartialUpdate(
		this PointerTypeSyntax node,
		Option<TypeSyntax> elementType = default,
		Option<SyntaxToken> asteriskToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FunctionPointerTypeSyntax PartialUpdate(
		this FunctionPointerTypeSyntax node,
		Option<SyntaxToken> delegateKeyword = default,
		Option<SyntaxToken> asteriskToken = default,
		Option<FunctionPointerCallingConventionSyntax?> callingConvention = default,
		Option<FunctionPointerParameterListSyntax> parameterList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FunctionPointerParameterListSyntax PartialUpdate(
		this FunctionPointerParameterListSyntax node,
		Option<SyntaxToken> lessThanToken = default,
		Option<SeparatedSyntaxList<FunctionPointerParameterSyntax>> parameters = default,
		Option<SyntaxToken> greaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FunctionPointerCallingConventionSyntax PartialUpdate(
		this FunctionPointerCallingConventionSyntax node,
		Option<SyntaxToken> managedOrUnmanagedKeyword = default,
		Option<FunctionPointerUnmanagedCallingConventionListSyntax?> unmanagedCallingConventionList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FunctionPointerUnmanagedCallingConventionListSyntax PartialUpdate(
		this FunctionPointerUnmanagedCallingConventionListSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<FunctionPointerUnmanagedCallingConventionSyntax>> callingConventions = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FunctionPointerUnmanagedCallingConventionSyntax PartialUpdate(
		this FunctionPointerUnmanagedCallingConventionSyntax node,
		Option<SyntaxToken> name = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static NullableTypeSyntax PartialUpdate(
		this NullableTypeSyntax node,
		Option<TypeSyntax> elementType = default,
		Option<SyntaxToken> questionToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TupleTypeSyntax PartialUpdate(
		this TupleTypeSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<TupleElementSyntax>> elements = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TupleElementSyntax PartialUpdate(
		this TupleElementSyntax node,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> identifier = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static OmittedTypeArgumentSyntax PartialUpdate(
		this OmittedTypeArgumentSyntax node,
		Option<SyntaxToken> omittedTypeArgumentToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RefTypeSyntax PartialUpdate(
		this RefTypeSyntax node,
		Option<SyntaxToken> refKeyword = default,
		Option<SyntaxToken> readOnlyKeyword = default,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ScopedTypeSyntax PartialUpdate(
		this ScopedTypeSyntax node,
		Option<SyntaxToken> scopedKeyword = default,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ParenthesizedExpressionSyntax PartialUpdate(
		this ParenthesizedExpressionSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TupleExpressionSyntax PartialUpdate(
		this TupleExpressionSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<ArgumentSyntax>> arguments = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PrefixUnaryExpressionSyntax PartialUpdate(
		this PrefixUnaryExpressionSyntax node,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax> operand = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AwaitExpressionSyntax PartialUpdate(
		this AwaitExpressionSyntax node,
		Option<SyntaxToken> awaitKeyword = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PostfixUnaryExpressionSyntax PartialUpdate(
		this PostfixUnaryExpressionSyntax node,
		Option<ExpressionSyntax> operand = default,
		Option<SyntaxToken> operatorToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static MemberAccessExpressionSyntax PartialUpdate(
		this MemberAccessExpressionSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> operatorToken = default,
		Option<SimpleNameSyntax> name = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConditionalAccessExpressionSyntax PartialUpdate(
		this ConditionalAccessExpressionSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax> whenNotNull = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static MemberBindingExpressionSyntax PartialUpdate(
		this MemberBindingExpressionSyntax node,
		Option<SyntaxToken> operatorToken = default,
		Option<SimpleNameSyntax> name = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ElementBindingExpressionSyntax PartialUpdate(
		this ElementBindingExpressionSyntax node,
		Option<BracketedArgumentListSyntax> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RangeExpressionSyntax PartialUpdate(
		this RangeExpressionSyntax node,
		Option<ExpressionSyntax?> leftOperand = default,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax?> rightOperand = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ImplicitElementAccessSyntax PartialUpdate(
		this ImplicitElementAccessSyntax node,
		Option<BracketedArgumentListSyntax> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BinaryExpressionSyntax PartialUpdate(
		this BinaryExpressionSyntax node,
		Option<ExpressionSyntax> left = default,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax> right = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AssignmentExpressionSyntax PartialUpdate(
		this AssignmentExpressionSyntax node,
		Option<ExpressionSyntax> left = default,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax> right = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConditionalExpressionSyntax PartialUpdate(
		this ConditionalExpressionSyntax node,
		Option<ExpressionSyntax> condition = default,
		Option<SyntaxToken> questionToken = default,
		Option<ExpressionSyntax> whenTrue = default,
		Option<SyntaxToken> colonToken = default,
		Option<ExpressionSyntax> whenFalse = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ThisExpressionSyntax PartialUpdate(
		this ThisExpressionSyntax node,
		Option<SyntaxToken> token = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BaseExpressionSyntax PartialUpdate(
		this BaseExpressionSyntax node,
		Option<SyntaxToken> token = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LiteralExpressionSyntax PartialUpdate(
		this LiteralExpressionSyntax node,
		Option<SyntaxToken> token = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static MakeRefExpressionSyntax PartialUpdate(
		this MakeRefExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RefTypeExpressionSyntax PartialUpdate(
		this RefTypeExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RefValueExpressionSyntax PartialUpdate(
		this RefValueExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> comma = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CheckedExpressionSyntax PartialUpdate(
		this CheckedExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DefaultExpressionSyntax PartialUpdate(
		this DefaultExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeOfExpressionSyntax PartialUpdate(
		this TypeOfExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SizeOfExpressionSyntax PartialUpdate(
		this SizeOfExpressionSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InvocationExpressionSyntax PartialUpdate(
		this InvocationExpressionSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<ArgumentListSyntax> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ElementAccessExpressionSyntax PartialUpdate(
		this ElementAccessExpressionSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<BracketedArgumentListSyntax> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ArgumentListSyntax PartialUpdate(
		this ArgumentListSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<ArgumentSyntax>> arguments = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BracketedArgumentListSyntax PartialUpdate(
		this BracketedArgumentListSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<ArgumentSyntax>> arguments = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ArgumentSyntax PartialUpdate(
		this ArgumentSyntax node,
		Option<NameColonSyntax?> nameColon = default,
		Option<SyntaxToken> refKindKeyword = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ExpressionColonSyntax PartialUpdate(
		this ExpressionColonSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static NameColonSyntax PartialUpdate(
		this NameColonSyntax node,
		Option<IdentifierNameSyntax> name = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DeclarationExpressionSyntax PartialUpdate(
		this DeclarationExpressionSyntax node,
		Option<TypeSyntax> type = default,
		Option<VariableDesignationSyntax> designation = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CastExpressionSyntax PartialUpdate(
		this CastExpressionSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AnonymousMethodExpressionSyntax PartialUpdate(
		this AnonymousMethodExpressionSyntax node,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> delegateKeyword = default,
		Option<ParameterListSyntax?> parameterList = default,
		Option<BlockSyntax> block = default,
		Option<ExpressionSyntax?> expressionBody = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SimpleLambdaExpressionSyntax PartialUpdate(
		this SimpleLambdaExpressionSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<ParameterSyntax> parameter = default,
		Option<SyntaxToken> arrowToken = default,
		Option<BlockSyntax?> block = default,
		Option<ExpressionSyntax?> expressionBody = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RefExpressionSyntax PartialUpdate(
		this RefExpressionSyntax node,
		Option<SyntaxToken> refKeyword = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ParenthesizedLambdaExpressionSyntax PartialUpdate(
		this ParenthesizedLambdaExpressionSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax?> returnType = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<SyntaxToken> arrowToken = default,
		Option<BlockSyntax?> block = default,
		Option<ExpressionSyntax?> expressionBody = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InitializerExpressionSyntax PartialUpdate(
		this InitializerExpressionSyntax node,
		Option<SyntaxToken> openBraceToken = default,
		Option<SeparatedSyntaxList<ExpressionSyntax>> expressions = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ImplicitObjectCreationExpressionSyntax PartialUpdate(
		this ImplicitObjectCreationExpressionSyntax node,
		Option<SyntaxToken> newKeyword = default,
		Option<ArgumentListSyntax> argumentList = default,
		Option<InitializerExpressionSyntax?> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ObjectCreationExpressionSyntax PartialUpdate(
		this ObjectCreationExpressionSyntax node,
		Option<SyntaxToken> newKeyword = default,
		Option<TypeSyntax> type = default,
		Option<ArgumentListSyntax?> argumentList = default,
		Option<InitializerExpressionSyntax?> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static WithExpressionSyntax PartialUpdate(
		this WithExpressionSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> withKeyword = default,
		Option<InitializerExpressionSyntax> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AnonymousObjectMemberDeclaratorSyntax PartialUpdate(
		this AnonymousObjectMemberDeclaratorSyntax node,
		Option<NameEqualsSyntax?> nameEquals = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AnonymousObjectCreationExpressionSyntax PartialUpdate(
		this AnonymousObjectCreationExpressionSyntax node,
		Option<SyntaxToken> newKeyword = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SeparatedSyntaxList<AnonymousObjectMemberDeclaratorSyntax>> initializers = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ArrayCreationExpressionSyntax PartialUpdate(
		this ArrayCreationExpressionSyntax node,
		Option<SyntaxToken> newKeyword = default,
		Option<ArrayTypeSyntax> type = default,
		Option<InitializerExpressionSyntax?> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ImplicitArrayCreationExpressionSyntax PartialUpdate(
		this ImplicitArrayCreationExpressionSyntax node,
		Option<SyntaxToken> newKeyword = default,
		Option<SyntaxToken> openBracketToken = default,
		Option<SyntaxTokenList> commas = default,
		Option<SyntaxToken> closeBracketToken = default,
		Option<InitializerExpressionSyntax> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static StackAllocArrayCreationExpressionSyntax PartialUpdate(
		this StackAllocArrayCreationExpressionSyntax node,
		Option<SyntaxToken> stackAllocKeyword = default,
		Option<TypeSyntax> type = default,
		Option<InitializerExpressionSyntax?> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ImplicitStackAllocArrayCreationExpressionSyntax PartialUpdate(
		this ImplicitStackAllocArrayCreationExpressionSyntax node,
		Option<SyntaxToken> stackAllocKeyword = default,
		Option<SyntaxToken> openBracketToken = default,
		Option<SyntaxToken> closeBracketToken = default,
		Option<InitializerExpressionSyntax> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CollectionExpressionSyntax PartialUpdate(
		this CollectionExpressionSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<CollectionElementSyntax>> elements = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ExpressionElementSyntax PartialUpdate(
		this ExpressionElementSyntax node,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SpreadElementSyntax PartialUpdate(
		this SpreadElementSyntax node,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static QueryExpressionSyntax PartialUpdate(
		this QueryExpressionSyntax node,
		Option<FromClauseSyntax> fromClause = default,
		Option<QueryBodySyntax> body = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static QueryBodySyntax PartialUpdate(
		this QueryBodySyntax node,
		Option<SyntaxList<QueryClauseSyntax>> clauses = default,
		Option<SelectOrGroupClauseSyntax> selectOrGroup = default,
		Option<QueryContinuationSyntax?> continuation = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FromClauseSyntax PartialUpdate(
		this FromClauseSyntax node,
		Option<SyntaxToken> fromKeyword = default,
		Option<TypeSyntax?> type = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> inKeyword = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LetClauseSyntax PartialUpdate(
		this LetClauseSyntax node,
		Option<SyntaxToken> letKeyword = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> equalsToken = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static JoinClauseSyntax PartialUpdate(
		this JoinClauseSyntax node,
		Option<SyntaxToken> joinKeyword = default,
		Option<TypeSyntax?> type = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> inKeyword = default,
		Option<ExpressionSyntax> inExpression = default,
		Option<SyntaxToken> onKeyword = default,
		Option<ExpressionSyntax> leftExpression = default,
		Option<SyntaxToken> equalsKeyword = default,
		Option<ExpressionSyntax> rightExpression = default,
		Option<JoinIntoClauseSyntax?> into = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static JoinIntoClauseSyntax PartialUpdate(
		this JoinIntoClauseSyntax node,
		Option<SyntaxToken> intoKeyword = default,
		Option<SyntaxToken> identifier = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static WhereClauseSyntax PartialUpdate(
		this WhereClauseSyntax node,
		Option<SyntaxToken> whereKeyword = default,
		Option<ExpressionSyntax> condition = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static OrderByClauseSyntax PartialUpdate(
		this OrderByClauseSyntax node,
		Option<SyntaxToken> orderByKeyword = default,
		Option<SeparatedSyntaxList<OrderingSyntax>> orderings = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static OrderingSyntax PartialUpdate(
		this OrderingSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> ascendingOrDescendingKeyword = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SelectClauseSyntax PartialUpdate(
		this SelectClauseSyntax node,
		Option<SyntaxToken> selectKeyword = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static GroupClauseSyntax PartialUpdate(
		this GroupClauseSyntax node,
		Option<SyntaxToken> groupKeyword = default,
		Option<ExpressionSyntax> groupExpression = default,
		Option<SyntaxToken> byKeyword = default,
		Option<ExpressionSyntax> byExpression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static QueryContinuationSyntax PartialUpdate(
		this QueryContinuationSyntax node,
		Option<SyntaxToken> intoKeyword = default,
		Option<SyntaxToken> identifier = default,
		Option<QueryBodySyntax> body = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static OmittedArraySizeExpressionSyntax PartialUpdate(
		this OmittedArraySizeExpressionSyntax node,
		Option<SyntaxToken> omittedArraySizeExpressionToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InterpolatedStringExpressionSyntax PartialUpdate(
		this InterpolatedStringExpressionSyntax node,
		Option<SyntaxToken> stringStartToken = default,
		Option<SyntaxList<InterpolatedStringContentSyntax>> contents = default,
		Option<SyntaxToken> stringEndToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static IsPatternExpressionSyntax PartialUpdate(
		this IsPatternExpressionSyntax node,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> isKeyword = default,
		Option<PatternSyntax> pattern = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ThrowExpressionSyntax PartialUpdate(
		this ThrowExpressionSyntax node,
		Option<SyntaxToken> throwKeyword = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static WhenClauseSyntax PartialUpdate(
		this WhenClauseSyntax node,
		Option<SyntaxToken> whenKeyword = default,
		Option<ExpressionSyntax> condition = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DiscardPatternSyntax PartialUpdate(
		this DiscardPatternSyntax node,
		Option<SyntaxToken> underscoreToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DeclarationPatternSyntax PartialUpdate(
		this DeclarationPatternSyntax node,
		Option<TypeSyntax> type = default,
		Option<VariableDesignationSyntax> designation = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static VarPatternSyntax PartialUpdate(
		this VarPatternSyntax node,
		Option<SyntaxToken> varKeyword = default,
		Option<VariableDesignationSyntax> designation = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RecursivePatternSyntax PartialUpdate(
		this RecursivePatternSyntax node,
		Option<TypeSyntax?> type = default,
		Option<PositionalPatternClauseSyntax?> positionalPatternClause = default,
		Option<PropertyPatternClauseSyntax?> propertyPatternClause = default,
		Option<VariableDesignationSyntax?> designation = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PositionalPatternClauseSyntax PartialUpdate(
		this PositionalPatternClauseSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<SubpatternSyntax>> subpatterns = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PropertyPatternClauseSyntax PartialUpdate(
		this PropertyPatternClauseSyntax node,
		Option<SyntaxToken> openBraceToken = default,
		Option<SeparatedSyntaxList<SubpatternSyntax>> subpatterns = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SubpatternSyntax PartialUpdate(
		this SubpatternSyntax node,
		Option<BaseExpressionColonSyntax?> expressionColon = default,
		Option<PatternSyntax> pattern = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConstantPatternSyntax PartialUpdate(
		this ConstantPatternSyntax node,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ParenthesizedPatternSyntax PartialUpdate(
		this ParenthesizedPatternSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<PatternSyntax> pattern = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RelationalPatternSyntax PartialUpdate(
		this RelationalPatternSyntax node,
		Option<SyntaxToken> operatorToken = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypePatternSyntax PartialUpdate(
		this TypePatternSyntax node,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BinaryPatternSyntax PartialUpdate(
		this BinaryPatternSyntax node,
		Option<PatternSyntax> left = default,
		Option<SyntaxToken> operatorToken = default,
		Option<PatternSyntax> right = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static UnaryPatternSyntax PartialUpdate(
		this UnaryPatternSyntax node,
		Option<SyntaxToken> operatorToken = default,
		Option<PatternSyntax> pattern = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ListPatternSyntax PartialUpdate(
		this ListPatternSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<PatternSyntax>> patterns = default,
		Option<SyntaxToken> closeBracketToken = default,
		Option<VariableDesignationSyntax?> designation = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SlicePatternSyntax PartialUpdate(
		this SlicePatternSyntax node,
		Option<SyntaxToken> dotDotToken = default,
		Option<PatternSyntax?> pattern = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InterpolatedStringTextSyntax PartialUpdate(
		this InterpolatedStringTextSyntax node,
		Option<SyntaxToken> textToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InterpolationSyntax PartialUpdate(
		this InterpolationSyntax node,
		Option<SyntaxToken> openBraceToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<InterpolationAlignmentClauseSyntax?> alignmentClause = default,
		Option<InterpolationFormatClauseSyntax?> formatClause = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InterpolationAlignmentClauseSyntax PartialUpdate(
		this InterpolationAlignmentClauseSyntax node,
		Option<SyntaxToken> commaToken = default,
		Option<ExpressionSyntax> value = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InterpolationFormatClauseSyntax PartialUpdate(
		this InterpolationFormatClauseSyntax node,
		Option<SyntaxToken> colonToken = default,
		Option<SyntaxToken> formatStringToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static GlobalStatementSyntax PartialUpdate(
		this GlobalStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BlockSyntax PartialUpdate(
		this BlockSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<StatementSyntax>> statements = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LocalFunctionStatementSyntax PartialUpdate(
		this LocalFunctionStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax> returnType = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LocalDeclarationStatementSyntax PartialUpdate(
		this LocalDeclarationStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> awaitKeyword = default,
		Option<SyntaxToken> usingKeyword = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<VariableDeclarationSyntax> declaration = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static VariableDeclarationSyntax PartialUpdate(
		this VariableDeclarationSyntax node,
		Option<TypeSyntax> type = default,
		Option<SeparatedSyntaxList<VariableDeclaratorSyntax>> variables = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static VariableDeclaratorSyntax PartialUpdate(
		this VariableDeclaratorSyntax node,
		Option<SyntaxToken> identifier = default,
		Option<BracketedArgumentListSyntax?> argumentList = default,
		Option<EqualsValueClauseSyntax?> initializer = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EqualsValueClauseSyntax PartialUpdate(
		this EqualsValueClauseSyntax node,
		Option<SyntaxToken> equalsToken = default,
		Option<ExpressionSyntax> value = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SingleVariableDesignationSyntax PartialUpdate(
		this SingleVariableDesignationSyntax node,
		Option<SyntaxToken> identifier = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DiscardDesignationSyntax PartialUpdate(
		this DiscardDesignationSyntax node,
		Option<SyntaxToken> underscoreToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ParenthesizedVariableDesignationSyntax PartialUpdate(
		this ParenthesizedVariableDesignationSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<VariableDesignationSyntax>> variables = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ExpressionStatementSyntax PartialUpdate(
		this ExpressionStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EmptyStatementSyntax PartialUpdate(
		this EmptyStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LabeledStatementSyntax PartialUpdate(
		this LabeledStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> colonToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static GotoStatementSyntax PartialUpdate(
		this GotoStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> gotoKeyword = default,
		Option<SyntaxToken> caseOrDefaultKeyword = default,
		Option<ExpressionSyntax?> expression = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BreakStatementSyntax PartialUpdate(
		this BreakStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> breakKeyword = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ContinueStatementSyntax PartialUpdate(
		this ContinueStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> continueKeyword = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ReturnStatementSyntax PartialUpdate(
		this ReturnStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> returnKeyword = default,
		Option<ExpressionSyntax?> expression = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ThrowStatementSyntax PartialUpdate(
		this ThrowStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> throwKeyword = default,
		Option<ExpressionSyntax?> expression = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static YieldStatementSyntax PartialUpdate(
		this YieldStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> yieldKeyword = default,
		Option<SyntaxToken> returnOrBreakKeyword = default,
		Option<ExpressionSyntax?> expression = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static WhileStatementSyntax PartialUpdate(
		this WhileStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> whileKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> condition = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DoStatementSyntax PartialUpdate(
		this DoStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> doKeyword = default,
		Option<StatementSyntax> statement = default,
		Option<SyntaxToken> whileKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> condition = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ForStatementSyntax PartialUpdate(
		this ForStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> forKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<VariableDeclarationSyntax?> declaration = default,
		Option<SeparatedSyntaxList<ExpressionSyntax>> initializers = default,
		Option<SyntaxToken> firstSemicolonToken = default,
		Option<ExpressionSyntax?> condition = default,
		Option<SyntaxToken> secondSemicolonToken = default,
		Option<SeparatedSyntaxList<ExpressionSyntax>> incrementors = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ForEachStatementSyntax PartialUpdate(
		this ForEachStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> awaitKeyword = default,
		Option<SyntaxToken> forEachKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> inKeyword = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ForEachVariableStatementSyntax PartialUpdate(
		this ForEachVariableStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> awaitKeyword = default,
		Option<SyntaxToken> forEachKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> variable = default,
		Option<SyntaxToken> inKeyword = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static UsingStatementSyntax PartialUpdate(
		this UsingStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> awaitKeyword = default,
		Option<SyntaxToken> usingKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<VariableDeclarationSyntax?> declaration = default,
		Option<ExpressionSyntax?> expression = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FixedStatementSyntax PartialUpdate(
		this FixedStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> fixedKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<VariableDeclarationSyntax> declaration = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CheckedStatementSyntax PartialUpdate(
		this CheckedStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> keyword = default,
		Option<BlockSyntax> block = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static UnsafeStatementSyntax PartialUpdate(
		this UnsafeStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> unsafeKeyword = default,
		Option<BlockSyntax> block = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LockStatementSyntax PartialUpdate(
		this LockStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> lockKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static IfStatementSyntax PartialUpdate(
		this IfStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> ifKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> condition = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<StatementSyntax> statement = default,
		Option<ElseClauseSyntax?> @else = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ElseClauseSyntax PartialUpdate(
		this ElseClauseSyntax node,
		Option<SyntaxToken> elseKeyword = default,
		Option<StatementSyntax> statement = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SwitchStatementSyntax PartialUpdate(
		this SwitchStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> switchKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> expression = default,
		Option<SyntaxToken> closeParenToken = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<SwitchSectionSyntax>> sections = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SwitchSectionSyntax PartialUpdate(
		this SwitchSectionSyntax node,
		Option<SyntaxList<SwitchLabelSyntax>> labels = default,
		Option<SyntaxList<StatementSyntax>> statements = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CasePatternSwitchLabelSyntax PartialUpdate(
		this CasePatternSwitchLabelSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<PatternSyntax> pattern = default,
		Option<WhenClauseSyntax?> whenClause = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CaseSwitchLabelSyntax PartialUpdate(
		this CaseSwitchLabelSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<ExpressionSyntax> value = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DefaultSwitchLabelSyntax PartialUpdate(
		this DefaultSwitchLabelSyntax node,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SwitchExpressionSyntax PartialUpdate(
		this SwitchExpressionSyntax node,
		Option<ExpressionSyntax> governingExpression = default,
		Option<SyntaxToken> switchKeyword = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SeparatedSyntaxList<SwitchExpressionArmSyntax>> arms = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SwitchExpressionArmSyntax PartialUpdate(
		this SwitchExpressionArmSyntax node,
		Option<PatternSyntax> pattern = default,
		Option<WhenClauseSyntax?> whenClause = default,
		Option<SyntaxToken> equalsGreaterThanToken = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TryStatementSyntax PartialUpdate(
		this TryStatementSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> tryKeyword = default,
		Option<BlockSyntax> block = default,
		Option<SyntaxList<CatchClauseSyntax>> catches = default,
		Option<FinallyClauseSyntax?> @finally = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CatchClauseSyntax PartialUpdate(
		this CatchClauseSyntax node,
		Option<SyntaxToken> catchKeyword = default,
		Option<CatchDeclarationSyntax?> declaration = default,
		Option<CatchFilterClauseSyntax?> filter = default,
		Option<BlockSyntax> block = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CatchDeclarationSyntax PartialUpdate(
		this CatchDeclarationSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<TypeSyntax> type = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CatchFilterClauseSyntax PartialUpdate(
		this CatchFilterClauseSyntax node,
		Option<SyntaxToken> whenKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<ExpressionSyntax> filterExpression = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FinallyClauseSyntax PartialUpdate(
		this FinallyClauseSyntax node,
		Option<SyntaxToken> finallyKeyword = default,
		Option<BlockSyntax> block = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CompilationUnitSyntax PartialUpdate(
		this CompilationUnitSyntax node,
		Option<SyntaxList<ExternAliasDirectiveSyntax>> externs = default,
		Option<SyntaxList<UsingDirectiveSyntax>> usings = default,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> endOfFileToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ExternAliasDirectiveSyntax PartialUpdate(
		this ExternAliasDirectiveSyntax node,
		Option<SyntaxToken> externKeyword = default,
		Option<SyntaxToken> aliasKeyword = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static UsingDirectiveSyntax PartialUpdate(
		this UsingDirectiveSyntax node,
		Option<SyntaxToken> globalKeyword = default,
		Option<SyntaxToken> usingKeyword = default,
		Option<SyntaxToken> staticKeyword = default,
		Option<SyntaxToken> unsafeKeyword = default,
		Option<NameEqualsSyntax?> alias = default,
		Option<TypeSyntax> namespaceOrType = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static NamespaceDeclarationSyntax PartialUpdate(
		this NamespaceDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> namespaceKeyword = default,
		Option<NameSyntax> name = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<ExternAliasDirectiveSyntax>> externs = default,
		Option<SyntaxList<UsingDirectiveSyntax>> usings = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> closeBraceToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FileScopedNamespaceDeclarationSyntax PartialUpdate(
		this FileScopedNamespaceDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> namespaceKeyword = default,
		Option<NameSyntax> name = default,
		Option<SyntaxToken> semicolonToken = default,
		Option<SyntaxList<ExternAliasDirectiveSyntax>> externs = default,
		Option<SyntaxList<UsingDirectiveSyntax>> usings = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AttributeListSyntax PartialUpdate(
		this AttributeListSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<AttributeTargetSpecifierSyntax?> target = default,
		Option<SeparatedSyntaxList<AttributeSyntax>> attributes = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AttributeTargetSpecifierSyntax PartialUpdate(
		this AttributeTargetSpecifierSyntax node,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AttributeSyntax PartialUpdate(
		this AttributeSyntax node,
		Option<NameSyntax> name = default,
		Option<AttributeArgumentListSyntax?> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AttributeArgumentListSyntax PartialUpdate(
		this AttributeArgumentListSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<AttributeArgumentSyntax>> arguments = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AttributeArgumentSyntax PartialUpdate(
		this AttributeArgumentSyntax node,
		Option<NameEqualsSyntax?> nameEquals = default,
		Option<NameColonSyntax?> nameColon = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static NameEqualsSyntax PartialUpdate(
		this NameEqualsSyntax node,
		Option<IdentifierNameSyntax> name = default,
		Option<SyntaxToken> equalsToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeParameterListSyntax PartialUpdate(
		this TypeParameterListSyntax node,
		Option<SyntaxToken> lessThanToken = default,
		Option<SeparatedSyntaxList<TypeParameterSyntax>> parameters = default,
		Option<SyntaxToken> greaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeParameterSyntax PartialUpdate(
		this TypeParameterSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxToken> varianceKeyword = default,
		Option<SyntaxToken> identifier = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ClassDeclarationSyntax PartialUpdate(
		this ClassDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax?> parameterList = default,
		Option<BaseListSyntax?> baseList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> closeBraceToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static StructDeclarationSyntax PartialUpdate(
		this StructDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax?> parameterList = default,
		Option<BaseListSyntax?> baseList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> closeBraceToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static InterfaceDeclarationSyntax PartialUpdate(
		this InterfaceDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax?> parameterList = default,
		Option<BaseListSyntax?> baseList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> closeBraceToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RecordDeclarationSyntax PartialUpdate(
		this RecordDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> keyword = default,
		Option<SyntaxToken> classOrStructKeyword = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax?> parameterList = default,
		Option<BaseListSyntax?> baseList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<MemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> closeBraceToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EnumDeclarationSyntax PartialUpdate(
		this EnumDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> enumKeyword = default,
		Option<SyntaxToken> identifier = default,
		Option<BaseListSyntax?> baseList = default,
		Option<SyntaxToken> openBraceToken = default,
		Option<SeparatedSyntaxList<EnumMemberDeclarationSyntax>> members = default,
		Option<SyntaxToken> closeBraceToken = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DelegateDeclarationSyntax PartialUpdate(
		this DelegateDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> delegateKeyword = default,
		Option<TypeSyntax> returnType = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EnumMemberDeclarationSyntax PartialUpdate(
		this EnumMemberDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> identifier = default,
		Option<EqualsValueClauseSyntax?> equalsValue = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BaseListSyntax PartialUpdate(
		this BaseListSyntax node,
		Option<SyntaxToken> colonToken = default,
		Option<SeparatedSyntaxList<BaseTypeSyntax>> types = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SimpleBaseTypeSyntax PartialUpdate(
		this SimpleBaseTypeSyntax node,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PrimaryConstructorBaseTypeSyntax PartialUpdate(
		this PrimaryConstructorBaseTypeSyntax node,
		Option<TypeSyntax> type = default,
		Option<ArgumentListSyntax> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeParameterConstraintClauseSyntax PartialUpdate(
		this TypeParameterConstraintClauseSyntax node,
		Option<SyntaxToken> whereKeyword = default,
		Option<IdentifierNameSyntax> name = default,
		Option<SyntaxToken> colonToken = default,
		Option<SeparatedSyntaxList<TypeParameterConstraintSyntax>> constraints = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConstructorConstraintSyntax PartialUpdate(
		this ConstructorConstraintSyntax node,
		Option<SyntaxToken> newKeyword = default,
		Option<SyntaxToken> openParenToken = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ClassOrStructConstraintSyntax PartialUpdate(
		this ClassOrStructConstraintSyntax node,
		Option<SyntaxToken> classOrStructKeyword = default,
		Option<SyntaxToken> questionToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeConstraintSyntax PartialUpdate(
		this TypeConstraintSyntax node,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DefaultConstraintSyntax PartialUpdate(
		this DefaultConstraintSyntax node,
		Option<SyntaxToken> defaultKeyword = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FieldDeclarationSyntax PartialUpdate(
		this FieldDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<VariableDeclarationSyntax> declaration = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EventFieldDeclarationSyntax PartialUpdate(
		this EventFieldDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> eventKeyword = default,
		Option<VariableDeclarationSyntax> declaration = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ExplicitInterfaceSpecifierSyntax PartialUpdate(
		this ExplicitInterfaceSpecifierSyntax node,
		Option<NameSyntax> name = default,
		Option<SyntaxToken> dotToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static MethodDeclarationSyntax PartialUpdate(
		this MethodDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax> returnType = default,
		Option<ExplicitInterfaceSpecifierSyntax?> explicitInterfaceSpecifier = default,
		Option<SyntaxToken> identifier = default,
		Option<TypeParameterListSyntax?> typeParameterList = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<SyntaxList<TypeParameterConstraintClauseSyntax>> constraintClauses = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static OperatorDeclarationSyntax PartialUpdate(
		this OperatorDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax> returnType = default,
		Option<ExplicitInterfaceSpecifierSyntax?> explicitInterfaceSpecifier = default,
		Option<SyntaxToken> operatorKeyword = default,
		Option<SyntaxToken> checkedKeyword = default,
		Option<SyntaxToken> operatorToken = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConversionOperatorDeclarationSyntax PartialUpdate(
		this ConversionOperatorDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> implicitOrExplicitKeyword = default,
		Option<ExplicitInterfaceSpecifierSyntax?> explicitInterfaceSpecifier = default,
		Option<SyntaxToken> operatorKeyword = default,
		Option<SyntaxToken> checkedKeyword = default,
		Option<TypeSyntax> type = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConstructorDeclarationSyntax PartialUpdate(
		this ConstructorDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> identifier = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<ConstructorInitializerSyntax?> initializer = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConstructorInitializerSyntax PartialUpdate(
		this ConstructorInitializerSyntax node,
		Option<SyntaxToken> colonToken = default,
		Option<SyntaxToken> thisOrBaseKeyword = default,
		Option<ArgumentListSyntax> argumentList = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DestructorDeclarationSyntax PartialUpdate(
		this DestructorDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> tildeToken = default,
		Option<SyntaxToken> identifier = default,
		Option<ParameterListSyntax> parameterList = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PropertyDeclarationSyntax PartialUpdate(
		this PropertyDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax> type = default,
		Option<ExplicitInterfaceSpecifierSyntax?> explicitInterfaceSpecifier = default,
		Option<SyntaxToken> identifier = default,
		Option<AccessorListSyntax?> accessorList = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<EqualsValueClauseSyntax?> initializer = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ArrowExpressionClauseSyntax PartialUpdate(
		this ArrowExpressionClauseSyntax node,
		Option<SyntaxToken> arrowToken = default,
		Option<ExpressionSyntax> expression = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EventDeclarationSyntax PartialUpdate(
		this EventDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> eventKeyword = default,
		Option<TypeSyntax> type = default,
		Option<ExplicitInterfaceSpecifierSyntax?> explicitInterfaceSpecifier = default,
		Option<SyntaxToken> identifier = default,
		Option<AccessorListSyntax?> accessorList = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static IndexerDeclarationSyntax PartialUpdate(
		this IndexerDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax> type = default,
		Option<ExplicitInterfaceSpecifierSyntax?> explicitInterfaceSpecifier = default,
		Option<SyntaxToken> thisKeyword = default,
		Option<BracketedParameterListSyntax> parameterList = default,
		Option<AccessorListSyntax?> accessorList = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AccessorListSyntax PartialUpdate(
		this AccessorListSyntax node,
		Option<SyntaxToken> openBraceToken = default,
		Option<SyntaxList<AccessorDeclarationSyntax>> accessors = default,
		Option<SyntaxToken> closeBraceToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static AccessorDeclarationSyntax PartialUpdate(
		this AccessorDeclarationSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<SyntaxToken> keyword = default,
		Option<BlockSyntax?> body = default,
		Option<ArrowExpressionClauseSyntax?> expressionBody = default,
		Option<SyntaxToken> semicolonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ParameterListSyntax PartialUpdate(
		this ParameterListSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<ParameterSyntax>> parameters = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BracketedParameterListSyntax PartialUpdate(
		this BracketedParameterListSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<ParameterSyntax>> parameters = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ParameterSyntax PartialUpdate(
		this ParameterSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax?> type = default,
		Option<SyntaxToken> identifier = default,
		Option<EqualsValueClauseSyntax?> @default = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static FunctionPointerParameterSyntax PartialUpdate(
		this FunctionPointerParameterSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static IncompleteMemberSyntax PartialUpdate(
		this IncompleteMemberSyntax node,
		Option<SyntaxList<AttributeListSyntax>> attributeLists = default,
		Option<SyntaxTokenList> modifiers = default,
		Option<TypeSyntax?> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static SkippedTokensTriviaSyntax PartialUpdate(
		this SkippedTokensTriviaSyntax node,
		Option<SyntaxTokenList> tokens = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DocumentationCommentTriviaSyntax PartialUpdate(
		this DocumentationCommentTriviaSyntax node,
		Option<SyntaxList<XmlNodeSyntax>> content = default,
		Option<SyntaxToken> endOfComment = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static TypeCrefSyntax PartialUpdate(
		this TypeCrefSyntax node,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static QualifiedCrefSyntax PartialUpdate(
		this QualifiedCrefSyntax node,
		Option<TypeSyntax> container = default,
		Option<SyntaxToken> dotToken = default,
		Option<MemberCrefSyntax> member = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static NameMemberCrefSyntax PartialUpdate(
		this NameMemberCrefSyntax node,
		Option<TypeSyntax> name = default,
		Option<CrefParameterListSyntax?> parameters = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static IndexerMemberCrefSyntax PartialUpdate(
		this IndexerMemberCrefSyntax node,
		Option<SyntaxToken> thisKeyword = default,
		Option<CrefBracketedParameterListSyntax?> parameters = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static OperatorMemberCrefSyntax PartialUpdate(
		this OperatorMemberCrefSyntax node,
		Option<SyntaxToken> operatorKeyword = default,
		Option<SyntaxToken> checkedKeyword = default,
		Option<SyntaxToken> operatorToken = default,
		Option<CrefParameterListSyntax?> parameters = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ConversionOperatorMemberCrefSyntax PartialUpdate(
		this ConversionOperatorMemberCrefSyntax node,
		Option<SyntaxToken> implicitOrExplicitKeyword = default,
		Option<SyntaxToken> operatorKeyword = default,
		Option<SyntaxToken> checkedKeyword = default,
		Option<TypeSyntax> type = default,
		Option<CrefParameterListSyntax?> parameters = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CrefParameterListSyntax PartialUpdate(
		this CrefParameterListSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SeparatedSyntaxList<CrefParameterSyntax>> parameters = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CrefBracketedParameterListSyntax PartialUpdate(
		this CrefBracketedParameterListSyntax node,
		Option<SyntaxToken> openBracketToken = default,
		Option<SeparatedSyntaxList<CrefParameterSyntax>> parameters = default,
		Option<SyntaxToken> closeBracketToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static CrefParameterSyntax PartialUpdate(
		this CrefParameterSyntax node,
		Option<SyntaxToken> refKindKeyword = default,
		Option<SyntaxToken> readOnlyKeyword = default,
		Option<TypeSyntax> type = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlElementSyntax PartialUpdate(
		this XmlElementSyntax node,
		Option<XmlElementStartTagSyntax> startTag = default,
		Option<SyntaxList<XmlNodeSyntax>> content = default,
		Option<XmlElementEndTagSyntax> endTag = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlElementStartTagSyntax PartialUpdate(
		this XmlElementStartTagSyntax node,
		Option<SyntaxToken> lessThanToken = default,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxList<XmlAttributeSyntax>> attributes = default,
		Option<SyntaxToken> greaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlElementEndTagSyntax PartialUpdate(
		this XmlElementEndTagSyntax node,
		Option<SyntaxToken> lessThanSlashToken = default,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxToken> greaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlEmptyElementSyntax PartialUpdate(
		this XmlEmptyElementSyntax node,
		Option<SyntaxToken> lessThanToken = default,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxList<XmlAttributeSyntax>> attributes = default,
		Option<SyntaxToken> slashGreaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlNameSyntax PartialUpdate(
		this XmlNameSyntax node,
		Option<XmlPrefixSyntax?> prefix = default,
		Option<SyntaxToken> localName = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlPrefixSyntax PartialUpdate(
		this XmlPrefixSyntax node,
		Option<SyntaxToken> prefix = default,
		Option<SyntaxToken> colonToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlTextAttributeSyntax PartialUpdate(
		this XmlTextAttributeSyntax node,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxToken> equalsToken = default,
		Option<SyntaxToken> startQuoteToken = default,
		Option<SyntaxTokenList> textTokens = default,
		Option<SyntaxToken> endQuoteToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlCrefAttributeSyntax PartialUpdate(
		this XmlCrefAttributeSyntax node,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxToken> equalsToken = default,
		Option<SyntaxToken> startQuoteToken = default,
		Option<CrefSyntax> cref = default,
		Option<SyntaxToken> endQuoteToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlNameAttributeSyntax PartialUpdate(
		this XmlNameAttributeSyntax node,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxToken> equalsToken = default,
		Option<SyntaxToken> startQuoteToken = default,
		Option<IdentifierNameSyntax> identifier = default,
		Option<SyntaxToken> endQuoteToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlTextSyntax PartialUpdate(
		this XmlTextSyntax node,
		Option<SyntaxTokenList> textTokens = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlCDataSectionSyntax PartialUpdate(
		this XmlCDataSectionSyntax node,
		Option<SyntaxToken> startCDataToken = default,
		Option<SyntaxTokenList> textTokens = default,
		Option<SyntaxToken> endCDataToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlProcessingInstructionSyntax PartialUpdate(
		this XmlProcessingInstructionSyntax node,
		Option<SyntaxToken> startProcessingInstructionToken = default,
		Option<XmlNameSyntax> name = default,
		Option<SyntaxTokenList> textTokens = default,
		Option<SyntaxToken> endProcessingInstructionToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static XmlCommentSyntax PartialUpdate(
		this XmlCommentSyntax node,
		Option<SyntaxToken> lessThanExclamationMinusMinusToken = default,
		Option<SyntaxTokenList> textTokens = default,
		Option<SyntaxToken> minusMinusGreaterThanToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static IfDirectiveTriviaSyntax PartialUpdate(
		this IfDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> ifKeyword = default,
		Option<ExpressionSyntax> condition = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default,
		Option<bool> branchTaken = default,
		Option<bool> conditionValue = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ElifDirectiveTriviaSyntax PartialUpdate(
		this ElifDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> elifKeyword = default,
		Option<ExpressionSyntax> condition = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default,
		Option<bool> branchTaken = default,
		Option<bool> conditionValue = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ElseDirectiveTriviaSyntax PartialUpdate(
		this ElseDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> elseKeyword = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default,
		Option<bool> branchTaken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EndIfDirectiveTriviaSyntax PartialUpdate(
		this EndIfDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> endIfKeyword = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static RegionDirectiveTriviaSyntax PartialUpdate(
		this RegionDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> regionKeyword = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static EndRegionDirectiveTriviaSyntax PartialUpdate(
		this EndRegionDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> endRegionKeyword = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ErrorDirectiveTriviaSyntax PartialUpdate(
		this ErrorDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> errorKeyword = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static WarningDirectiveTriviaSyntax PartialUpdate(
		this WarningDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> warningKeyword = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static BadDirectiveTriviaSyntax PartialUpdate(
		this BadDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> identifier = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static DefineDirectiveTriviaSyntax PartialUpdate(
		this DefineDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> defineKeyword = default,
		Option<SyntaxToken> name = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static UndefDirectiveTriviaSyntax PartialUpdate(
		this UndefDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> undefKeyword = default,
		Option<SyntaxToken> name = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LineDirectiveTriviaSyntax PartialUpdate(
		this LineDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> lineKeyword = default,
		Option<SyntaxToken> line = default,
		Option<SyntaxToken> @file = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LineDirectivePositionSyntax PartialUpdate(
		this LineDirectivePositionSyntax node,
		Option<SyntaxToken> openParenToken = default,
		Option<SyntaxToken> line = default,
		Option<SyntaxToken> commaToken = default,
		Option<SyntaxToken> character = default,
		Option<SyntaxToken> closeParenToken = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LineSpanDirectiveTriviaSyntax PartialUpdate(
		this LineSpanDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> lineKeyword = default,
		Option<LineDirectivePositionSyntax> start = default,
		Option<SyntaxToken> minusToken = default,
		Option<LineDirectivePositionSyntax> end = default,
		Option<SyntaxToken> characterOffset = default,
		Option<SyntaxToken> @file = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PragmaWarningDirectiveTriviaSyntax PartialUpdate(
		this PragmaWarningDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> pragmaKeyword = default,
		Option<SyntaxToken> warningKeyword = default,
		Option<SyntaxToken> disableOrRestoreKeyword = default,
		Option<SeparatedSyntaxList<ExpressionSyntax>> errorCodes = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static PragmaChecksumDirectiveTriviaSyntax PartialUpdate(
		this PragmaChecksumDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> pragmaKeyword = default,
		Option<SyntaxToken> checksumKeyword = default,
		Option<SyntaxToken> @file = default,
		Option<SyntaxToken> guid = default,
		Option<SyntaxToken> bytes = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ReferenceDirectiveTriviaSyntax PartialUpdate(
		this ReferenceDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> referenceKeyword = default,
		Option<SyntaxToken> @file = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static LoadDirectiveTriviaSyntax PartialUpdate(
		this LoadDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> loadKeyword = default,
		Option<SyntaxToken> @file = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static ShebangDirectiveTriviaSyntax PartialUpdate(
		this ShebangDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> exclamationToken = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
	public static NullableDirectiveTriviaSyntax PartialUpdate(
		this NullableDirectiveTriviaSyntax node,
		Option<SyntaxToken> hashToken = default,
		Option<SyntaxToken> nullableKeyword = default,
		Option<SyntaxToken> settingToken = default,
		Option<SyntaxToken> targetToken = default,
		Option<SyntaxToken> endOfDirectiveToken = default,
		Option<bool> isActive = default )
		=> throw new NotSupportedException("This method is generated by code in a private repository.");
}
