// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Caravela.Framework.DesignTime.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "32e6d4ce-74c3-455d-bf30-34974837018e";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidMyCommandPackageCmdSetString = "3bb64001-1a69-46a1-b54c-e1ef2d4bc33a";
        public static Guid guidMyCommandPackageCmdSet = new Guid(guidMyCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyCommandId = 0x0100;
    }
}